import React from 'react';
import Link from 'next/link';
import { ArrowLeft, Scale } from 'lucide-react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Terms of Service | Dezprox",
  description: "Terms of service for the estimation platform.",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gray-50/50 flex flex-col font-sans">
      <div className="max-w-3xl mx-auto px-4 py-12 w-full flex-grow">
        <Link href="/" className="inline-flex items-center text-sm font-bold text-dezprox-primary hover:text-dezprox-accent mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Estimator
        </Link>
        
        <div className="bg-white rounded-2xl shadow-sm border border-gray-150 p-8 md:p-12">
          <div className="flex items-center space-x-3 mb-2">
            <div className="w-10 h-10 rounded-xl bg-dezprox-accent/10 flex items-center justify-center">
              <Scale className="w-5 h-5 text-dezprox-accent" />
            </div>
            <h1 className="text-3xl font-black text-dezprox-primary tracking-tight">Terms of Service</h1>
          </div>
          <p className="text-xs text-gray-400 font-bold uppercase tracking-wider mb-8">
            Last updated: [DATE]
          </p>
          
          <div className="prose prose-sm md:prose-base prose-gray max-w-none text-dezprox-text/80 space-y-8">
            
            <section>
              <h2 className="text-lg font-black text-dezprox-primary mb-3">Estimates</h2>
              <p>
                Estimates generated by the platform are intended as an initial indication of potential project costs and are not necessarily a final quotation, contract, or binding commitment unless explicitly confirmed by the company. Final pricing may vary based on detailed scope review and final requirements.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-black text-dezprox-primary mb-3">Information Provided by Users</h2>
              <p>
                By providing information through the platform, you represent that the details are accurate and that you have the right to share such information for the purpose of receiving an estimate or consultation. 
              </p>
            </section>

            <section>
              <h2 className="text-lg font-black text-dezprox-primary mb-3">Acceptable Use</h2>
              <p>
                You agree to use this platform solely for its intended purpose of configuring service estimates and submitting legitimate enquiries. You may not use the platform for any unlawful purpose, or to submit false, misleading, or malicious data.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-black text-dezprox-primary mb-3">Availability</h2>
              <p>
                We strive to keep the platform accessible, but we do not guarantee continuous, uninterrupted, or error-free operation. The platform may be temporarily unavailable for maintenance or due to circumstances beyond our control.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-black text-dezprox-primary mb-3">Third-Party Services</h2>
              <p>
                The platform may interact with third-party service providers (such as hosting or database providers) to operate effectively. Your use of the platform acknowledges that such third-party interactions are essential for its functionality.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-black text-dezprox-primary mb-3">Changes</h2>
              <p>
                We reserve the right to modify these Terms of Service at any time. Any updates will be reflected by the &quot;Last updated&quot; date on this page. Continued use of the platform following modifications indicates your acceptance of the revised terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-black text-dezprox-primary mb-3">Contact</h2>
              <p>
                For questions regarding these Terms of Service, please contact us at: <br />
                <span className="font-mono text-dezprox-accent font-bold">info@dezprox.com</span>
              </p>
            </section>

          </div>
        </div>
      </div>
    </div>
  );
}
