"use client";

import React, { useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Estimate } from "@/lib/types";
import { endpoints } from "@/lib/api/endpoints";
import { Search, Trash2, Eye, X, Check, XCircle, RefreshCw } from "lucide-react";

export default function EstimateManagement() {
  const [estimates, setEstimates] = useState<Estimate[]>([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [currency, setCurrency] = useState("₹");
  const [loading, setLoading] = useState(true);
  
  // Details Modal state
  const [viewingEstimate, setViewingEstimate] = useState<Estimate | null>(null);

  const fetchEstimates = async () => {
    try {
      setLoading(true);
      const res = await endpoints.adminGetEstimates(1, 100);
      if (res.success && res.data) {
        setEstimates(res.data.items || []);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  React.useEffect(() => {
    fetchEstimates();
    endpoints.getPublicSettings().then((res) => {
      if (res.success && res.data?.currency) {
        setCurrency(res.data.currency);
      }
    }).catch(console.error);
  }, []);

  const handleDelete = async (id: string) => {
    try {
      await endpoints.adminDeleteEstimate(id);
      fetchEstimates();
    } catch (err: any) {
      console.error(err);
      alert(`Failed to delete estimate: ${err.message || err}`);
    }
  };

  const handleUpdateStatus = async (id: string, status: Estimate["status"]) => {
    try {
      await endpoints.adminUpdateEstimateStatus(id, status);
      fetchEstimates();
      if (viewingEstimate && viewingEstimate.id === id) {
        setViewingEstimate({ ...viewingEstimate, status });
      }
    } catch (err) {
      console.error(err);
    }
  };

  // Filter and search
  const filteredEstimates = estimates.filter((est) => {
    const matchesSearch = 
      est.customerName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      est.customerEmail.toLowerCase().includes(searchTerm.toLowerCase()) ||
      est.id.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesStatus = statusFilter === "all" || est.status === statusFilter;

    return matchesSearch && matchesStatus;
  });

  return (
    <div className="space-y-8 font-sans">
      <div>
        <h1 className="text-3xl font-extrabold text-dezprox-primary tracking-tight">
          Estimate Slips Management
        </h1>
        <p className="text-dezprox-text/60 mt-1 text-sm">
          Track and verify custom pricing estimates generated by prospective leads.
        </p>
      </div>

      {/* Filter Toolbar */}
      <Card className="p-4 border-gray-100 shadow-sm bg-white flex flex-col md:flex-row gap-4 items-center justify-between">
        <div className="relative w-full md:max-w-md">
          <Search className="absolute left-3 top-3.5 w-4 h-4 text-gray-400" />
          <Input
            placeholder="Search by customer name, email, or Estimate ID..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-10"
          />
        </div>
        <div className="w-full md:w-48">
          <Select
            options={[
              { value: "all", label: "All Statuses" },
              { value: "pending", label: "Pending Review" },
              { value: "approved", label: "Approved" },
              { value: "completed", label: "Completed" },
              { value: "rejected", label: "Rejected" },
            ]}
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
          />
        </div>
      </Card>

      {/* Estimates Table */}
      <Card className="overflow-hidden border-gray-100 shadow-sm bg-white">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-sm">
            <thead>
              <tr className="bg-gray-50 border-b border-gray-100 text-dezprox-primary font-bold text-xs uppercase tracking-wider">
                <th className="p-4 pl-6">ID</th>
                <th className="p-4">Customer</th>
                <th className="p-4">Selected Services</th>
                <th className="p-4">Est. Total Price</th>
                <th className="p-4">Created Date</th>
                <th className="p-4">Status</th>
                <th className="p-4 pr-6 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {filteredEstimates.length === 0 ? (
                <tr>
                  <td colSpan={7} className="p-8 text-center text-gray-400">
                    No estimates found matching your filters.
                  </td>
                </tr>
              ) : (
                filteredEstimates.map((est) => (
                  <tr key={est.id} className="hover:bg-slate-50/40 transition-colors">
                    <td className="p-4 pl-6 font-mono font-bold text-dezprox-primary">{est.id}</td>
                    <td className="p-4">
                      <span className="font-bold text-dezprox-primary block">{est.customerName}</span>
                      <span className="text-xs text-gray-400 block">{est.customerEmail}</span>
                      {est.customerPhone && <span className="text-[10px] text-gray-400 block">{est.customerPhone}</span>}
                      {est.customerCompany && <span className="text-[10px] bg-gray-50 border border-gray-150 px-1.5 py-0.5 rounded text-gray-500 font-semibold inline-block mt-0.5">{est.customerCompany}</span>}
                    </td>
                    <td className="p-4">
                      <div className="flex flex-wrap gap-1">
                        {est.serviceNames.map((s, idx) => (
                          <Badge key={idx} variant="secondary" className="text-[9px] py-0.5">
                            {s}
                          </Badge>
                        ))}
                      </div>
                    </td>
                    <td className="p-4 font-black text-dezprox-primary">
                      {currency}{Math.round(est.totalPrice).toLocaleString()}
                    </td>
                    <td className="p-4 text-xs text-gray-500 font-semibold">
                      {new Date(est.createdDate).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}
                    </td>
                    <td className="p-4">
                      <Badge 
                        variant={
                          est.status === "approved" || est.status === "completed" 
                            ? "accent" 
                            : est.status === "rejected" 
                              ? "outline" 
                              : "secondary"
                        } 
                        className={`capitalize font-bold text-[10px] ${
                          est.status === "rejected" ? "bg-red-50 text-red-600 border-red-100" : ""
                        }`}
                      >
                        {est.status}
                      </Badge>
                    </td>
                    <td className="p-4 pr-6 text-right whitespace-nowrap space-x-2">
                      <button
                        onClick={() => setViewingEstimate(est)}
                        className="p-1.5 border border-gray-200 text-gray-500 rounded-lg hover:text-dezprox-primary hover:bg-gray-50 transition-all cursor-pointer"
                        title="View Details"
                      >
                        <Eye className="w-3.5 h-3.5" />
                      </button>
                      <button
                        onClick={() => handleDelete(est.id)}
                        className="p-1.5 border border-red-100 text-red-500 rounded-lg hover:text-red-600 hover:bg-red-50 transition-all cursor-pointer"
                        title="Delete Estimate"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </Card>

      {/* Details Modal Overlay */}
      {viewingEstimate && (
        <div className="fixed inset-0 bg-black/30 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-card max-w-2xl w-full p-6 shadow-2xl relative border border-gray-100 animate-in fade-in zoom-in-95 duration-200 overflow-y-auto max-h-[90vh]">
            <button 
              onClick={() => setViewingEstimate(null)}
              className="absolute right-4 top-4 p-1 text-gray-400 hover:text-dezprox-primary transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="border-b border-gray-100 pb-4 mb-4">
              <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block font-mono">Estimate Details</span>
              <h3 className="text-xl font-bold text-dezprox-primary mt-1">
                Ref ID: {viewingEstimate.id}
              </h3>
            </div>

            <div className="space-y-6">
              {/* Customer summary */}
              <div className="grid grid-cols-2 gap-4 text-xs leading-relaxed bg-gray-50 p-4 rounded-xl">
                <div>
                  <span className="text-gray-400 block font-semibold">Customer Name</span>
                  <span className="font-bold text-dezprox-primary text-sm">{viewingEstimate.customerName}</span>
                </div>
                <div>
                  <span className="text-gray-400 block font-semibold">Customer Email</span>
                  <span className="font-bold text-dezprox-primary text-sm">{viewingEstimate.customerEmail}</span>
                </div>
                {viewingEstimate.customerPhone && (
                  <div>
                    <span className="text-gray-400 block font-semibold">Customer Phone</span>
                    <span className="font-bold text-dezprox-primary text-sm">{viewingEstimate.customerPhone}</span>
                  </div>
                )}
                {viewingEstimate.customerCompany && (
                  <div>
                    <span className="text-gray-400 block font-semibold">Company</span>
                    <span className="font-bold text-dezprox-primary text-sm">{viewingEstimate.customerCompany}</span>
                  </div>
                )}
                {viewingEstimate.estimateRange && (
                  <div>
                    <span className="text-gray-400 block font-semibold">Estimate Range</span>
                    <span className="font-bold text-dezprox-primary text-sm">{viewingEstimate.estimateRange}</span>
                  </div>
                )}
                <div>
                  <span className="text-gray-400 block font-semibold">Generated Date</span>
                  <span className="font-bold text-dezprox-primary">
                    {new Date(viewingEstimate.createdDate).toLocaleString("en-IN")}
                  </span>
                </div>
                <div>
                  <span className="text-gray-400 block font-semibold">Total Cost</span>
                  <span className="font-black text-dezprox-primary text-sm">
                    {currency}{Math.round(viewingEstimate.totalPrice).toLocaleString()}
                  </span>
                </div>
              </div>

              {/* Status Update Quick Bar */}
              <div className="flex flex-wrap items-center justify-between gap-3 border border-gray-100 p-4 rounded-xl bg-slate-50/30">
                <span className="text-xs font-bold text-gray-500 uppercase tracking-wider">
                  Update Lead Status:
                </span>
                <div className="flex space-x-2">
                  <button
                    onClick={() => handleUpdateStatus(viewingEstimate.id, "approved")}
                    className={`px-3 py-1.5 rounded-full text-xs font-bold transition-all cursor-pointer flex items-center gap-1 ${
                      viewingEstimate.status === "approved"
                        ? "bg-dezprox-primary text-white"
                        : "bg-white text-dezprox-primary border border-gray-200 hover:bg-gray-50"
                    }`}
                  >
                    <Check className="w-3 h-3 text-dezprox-accent" />
                    Approve
                  </button>
                  <button
                    onClick={() => handleUpdateStatus(viewingEstimate.id, "completed")}
                    className={`px-3 py-1.5 rounded-full text-xs font-bold transition-all cursor-pointer flex items-center gap-1 ${
                      viewingEstimate.status === "completed"
                        ? "bg-emerald-600 text-white"
                        : "bg-white text-gray-600 border border-gray-200 hover:bg-gray-50"
                    }`}
                  >
                    <Check className="w-3 h-3" />
                    Complete
                  </button>
                  <button
                    onClick={() => handleUpdateStatus(viewingEstimate.id, "rejected")}
                    className={`px-3 py-1.5 rounded-full text-xs font-bold transition-all cursor-pointer flex items-center gap-1 ${
                      viewingEstimate.status === "rejected"
                        ? "bg-red-500 text-white"
                        : "bg-white text-red-500 border border-gray-200 hover:bg-red-50"
                    }`}
                  >
                    <XCircle className="w-3 h-3" />
                    Reject
                  </button>
                  <button
                    onClick={() => handleUpdateStatus(viewingEstimate.id, "pending")}
                    className={`px-3 py-1.5 rounded-full text-xs font-bold transition-all cursor-pointer flex items-center gap-1 ${
                      viewingEstimate.status === "pending"
                        ? "bg-gray-400 text-white"
                        : "bg-white text-gray-500 border border-gray-200 hover:bg-gray-50"
                    }`}
                  >
                    <RefreshCw className="w-3 h-3" />
                    Reset
                  </button>
                </div>
              </div>

              {/* Customer Notes / Messages */}
              {viewingEstimate.notes ? (
                <div className="space-y-2">
                  <span className="text-xs font-bold text-gray-400 uppercase tracking-widest block">Customer Notes</span>
                  <div className="border border-gray-100 p-4 rounded-xl bg-slate-50/20 text-xs text-dezprox-primary font-normal leading-relaxed">
                    {String(viewingEstimate.notes)}
                  </div>
                </div>
              ) : null}

              {/* Questionnaire Answers */}
              {viewingEstimate.answers && Object.keys(viewingEstimate.answers).length > 0 ? (
                <div className="space-y-3">
                  <span className="text-xs font-bold text-gray-400 uppercase tracking-widest block">Questionnaire Responses</span>
                  <div className="border border-gray-100 rounded-xl divide-y divide-gray-100 overflow-hidden bg-white">
                    {Object.entries(viewingEstimate.answers).map(([serviceId, serviceAnswers]: [string, Record<string, unknown>]) => {
                      if (!serviceAnswers || Object.keys(serviceAnswers).length === 0) return null;
                      
                      return (
                        <div key={serviceId} className="p-4 space-y-2">
                          <span className="font-bold text-xs text-dezprox-accent uppercase tracking-wider block">
                            Service ID: {serviceId}
                          </span>
                          <div className="space-y-2">
                            {Object.entries(serviceAnswers).map(([qId, val]: [string, unknown]) => {
                              if (qId === "selected-package") {
                                return (
                                  <div key={qId} className="text-xs">
                                    <span className="text-gray-400 font-semibold mr-1.5">Selected Package Tier:</span>
                                    <span className="font-bold text-dezprox-primary">{String(val)}</span>
                                  </div>
                                );
                              }
                              if (qId === "pricing-components") {
                                return (
                                  <div key={qId} className="text-xs">
                                    <span className="text-gray-400 font-semibold mr-1.5">Selected Add-on IDs:</span>
                                    <span className="font-bold text-dezprox-primary">{Array.isArray(val) ? val.join(", ") : String(val)}</span>
                                  </div>
                                );
                              }
                              if (qId === "pricing-component-units") {
                                return null; // Displayed elsewhere or omitted for clean presentation
                              }
                              
                              let displayVal = "";
                              if (Array.isArray(val)) {
                                displayVal = val.join(", ");
                              } else if (typeof val === "boolean") {
                                displayVal = val ? "Yes" : "No";
                              } else {
                                displayVal = String(val);
                              }

                              return (
                                <div key={qId} className="text-xs flex flex-col md:flex-row md:justify-between border-b border-gray-50/50 pb-1 last:border-0 last:pb-0">
                                  <span className="text-gray-500 font-medium">{qId}:</span>
                                  <span className="font-bold text-dezprox-primary text-right">{displayVal}</span>
                                </div>
                              );
                            })}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ) : null}

              {/* Itemized breakdown (if dynamic calculate breakdown exists) */}
              {viewingEstimate.breakdown?.services ? (
                <div className="space-y-3">
                  <span className="text-xs font-bold text-gray-400 uppercase tracking-widest block">Cost Breakdown Items</span>
                  <div className="border border-gray-100 rounded-xl divide-y divide-gray-100 overflow-hidden">
                    {(viewingEstimate.breakdown.services as any[]).map((srv: any, idx: number) => (
                      <div key={idx} className="p-4 space-y-2">
                        <div className="flex justify-between items-center">
                          <span className="font-bold text-dezprox-primary text-sm">{srv.serviceName}</span>
                          <span className="text-xs font-black text-dezprox-primary bg-gray-50 px-2 py-0.5 rounded">
                            {currency}{Math.round(srv.totalCost).toLocaleString()}
                          </span>
                        </div>
                        <ul className="text-xs text-gray-400 space-y-1 pl-4 list-disc">
                          {srv.details?.filter((d: any) => d.type !== "base").map((d: any, dIdx: number) => (
                            <li key={dIdx} className="flex justify-between">
                              <span>{d.name}</span>
                              <span className="font-mono text-gray-500 text-[10px]">{d.costLabel}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    ))}
                  </div>
                </div>
              ) : null}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
